apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ery7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zvyp-tenant/rhtap-demo-app/hacbs-test-project-ery7@sha256:04f57b38954ed6c623fd4fe7416c55dba34f79257cc1e6702d8a414d018532cb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
